Buttons/index.html, index.html, style.css
I have successfully Improve Navbar UI Best look with hover button. I hope you will like it .Thank you :)
=> Improve Navbar UI Best look with hover button

Alerts-MrAfonso/index.html, Alerts-MrAfonso/style.css, index.html
- Fixed some links in `index.html`
- Added `Alerts` to the design button list in `index.html`
» Has Info, Danger, Success, Dark & Warning alerts with respective colors and icon.
» Has a `Go Back` button to go to the main page.
Follows the same style as the main page.
=> Added Alerts designs.

Buttons/index.html, Buttons/style.css
Added buttons with changing colors to index.html
=> Added buttons with changing colors

PriceCard/index.html, PriceCard/style.css
=> Create price card

EventCard/index.html, EventCard/style.css
=> add event card

index.html, style.css
=> Improve html and css

Alerts-MrAfonso/index.html, sidebarNav/index.html, sidebarNav/style.css
I am adding side bar navigation
=> add side bar

.vscode/settings.json, style.css
#50 
can change animation or color if you don't like it!
=> Improve Buttons

index.html, style.css
=> Added hamburger menu

index.html, style.css
Hello! @surajondev Please check my pr.
=> Added Footer #59

index.html, style.css
Reverts surajondev/UI-UX-Design#68
Reason: Broke some components of the main page.
=> Revert "Added hamburger menu"

css-only-model/index.html, css-only-model/style.css
=> model using CSS added

css-only-Accordion/index.html, css-only-Accordion/style.css
=> css only accordion added

Share-Button/index.html, Share-Button/style.css
It's a cool share button made with the help of CSS. One can use it on their website for making the user experience of a user more easy and cool.
=> New cool share button added

Buttons/index.html, Cards-MrAfonso/style.css, index.html, style.css
Changes the color and hover of the button 
Add link to social icons button 
Change the card hover, color
=> Changes the style in home

Buttons/index.html
When you bringing their mouse it change the background color ,color and border
=> Add hover Button

Timeline/index.html
I  have added  code for Timeline ui design
=> Code for Timeline UI Design

Modals/index.html, Modals/style.css
=> add modal card

Pop-up/index.html, Pop-up/style.css
=> add pop up card

Select User/index.html, Select User/style.css, index.html
Check out the changes that I've made :) It's a bit more interactive. I've also added a  'back button'. Hope you like it
=> Revamped 'Select User'

Cards-MrAfonso/index.html
@surajondev kindly add hacktoberfest label and merge it. Thank you
=> bug-fix 404 error in goback of cards-Mr.Afonso page

style.css
@surajondev kindly add hacktoberfest label and merge it. Thank you
=> feat-add hover effect to social media handles

FileUploader/index.html, FileUploader/style.css
=> add file uploader

ReviewCard/index.html, ReviewCard/style.css
=> Add review card

Alerts-MrAfonso/index.html
I have changed the href of  "Go Back" in Alerts file. Before it was not going back to the home page. Now, it is navigated to home page
=> alert go back sorted

Subsrciption_Cards/index.html, index.html
This pull request addresses issue #109.
Changes Made:
*Added Subscription Cards HTML: Created an HTML file for Subscription Cards, making it easier for users to understand and compare different subscription options at a glance.
*Linked in Main Index.html: Linked the Subscription Cards HTML file in the main index.html, ensuring easy access for users from the homepage.
Additional Enhancements:
In addition to the initial changes mentioned in issue #109, I have also completed the following tasks to further enhance Subscription Cards:
*Styled Subscription Cards: Applied CSS styles to enhance the visual appeal and maintain consistency with the existing UI components.
*Testing: Conducted thorough testing to ensure the functionality and appearance of Subscription Cards for a seamless user …
=> Add Subscription Cards HTML and Link in Main Index.html

Buttons/index.html, Buttons/style.css, CONTRIBUTION.md
This pull request addresses issue #111 
Changes made:
- Added Go Back button to top of page in same style as go back button on Alerts page.
Will you please add hacktoberfest-accepted label?
=> Add Go Back Feature to Buttons Page

UI_TimeLine/index.html, UI_TimeLine/style.css
##Issue 
Fixes : Issue #128 
Enhance UI-UX-Design Repository with a Timeline Feature
I propose adding a timeline feature to our UI-UX-Design repository to provide users with a visual representation of project timelines and milestones, improving the user experience and educational value. This feature is currently not available and aligns with our mission to promote UI/UX design skills.
=> TimeLine_UI/UX

button-animation/index.html, button-animation/style.css
I have added a new button CSS to the repository
=> Added new button css

LoginPage/index.html, LoginPage/style.css
Crteated the Login and Signup page for the website #125
=> Updated the login page @nirmalyax
